### ISSUE TITLE
Select System Mode via a button

### ISSUE THREAD

**Issue by borpin** [lnagel/hass-komfovent#41]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/lnagel/hass-komfovent/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

On my existing system, I have buttons for the mode selection, like the Komfovent Web interface. It would be good to be able to replicate this.

```
type: custom:button-card
entity: sensor.komfovent_operation_mode
color: grey
tap_action:
  action: call-service
  service: modbus.write_register
  service_data:
    address: 4
    hub: Komfovent
    unit: 1
    value: 2
hold_action:
  action: none
name: Normal
show_name: true
icon: mdi:home-account
color_type: card
state:
  - value: Normal
    color: CornflowerBlue
```

![Image](https://github.com/user-attachments/assets/9643a891-9505-40b7-a3b8-d52852ac9df4)

### Describe the solution you'd like

Replicate the button interface on the Komfovent Web Interface

### Describe alternatives you've considered

Write to the Modbus directly

### Additional context

Nil

**Comment by lnagel** [comment]
Theoretically, could you implement the buttons using the existing `komfovent_current_mode` select entity, simply by writing a new value to it? The constants `away`, `normal`, `intensive` and `boost` should be accepted.

**Comment by lnagel** [comment]
Current draft for the `set_mode` action + button config, what do you think?

```
show_name: true
show_icon: true
type: button
entity: select.komfovent_current_mode
name: Normal
icon: mdi:home
show_state: false
tap_action:
  action: perform-action
  perform_action: komfovent.set_mode
  target: {}
  data:
    config_entry: 01JPCJ33S8XJWA4E31B8N6NKV9
    mode: normal
```

![Image](https://github.com/user-attachments/assets/71889898-3953-450f-8be9-b97868b65975)
