### ISSUE TITLE
Return system status

### ISSUE THREAD

**Issue by borpin** [lnagel/hass-komfovent#44]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/lnagel/hass-komfovent/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Please decode system status (register 900) and return as individual Binary sensors. Primarily it is the only way to detect **Flow Down**.

### Describe the solution you'd like

I did this on my system using

```
inary_sensor:
  - platform: template
    sensors:
      komfovent_status_starting:
        friendly_name: "Komfovent Status - Starting"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(1) > 0 }}"
      komfovent_status_stopping:
        friendly_name: "Komfovent Status - Stopping"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(2) > 0 }}"
      komfovent_status_fan:
        friendly_name: "Komfovent Status - Fan"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(4) > 0 }}"
      komfovent_status_rotor:
        friendly_name: "Komfovent Status - Rotor"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(8) > 0 }}"
      komfovent_status_heating:
        friendly_name: "Komfovent Status - Heating"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(16) > 0 }}"
      komfovent_status_cooling:
        friendly_name: "Komfovent Status - Cooling"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(32) > 0 }}"
      komfovent_status_heatingdenied:
        friendly_name: "Komfovent Status - Heating Denied"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(64) > 0 }}"
      komfovent_status_coolingdenied:
        friendly_name: "Komfovent Status - Cooling Denied"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(128) > 0 }}"
      komfovent_status_flow_down:
        friendly_name: "Komfovent Status - Flow Down"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(256) > 0 }}"
      komfovent_status_free_heating:
        friendly_name: "Komfovent Status - Free Heating"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(512) > 0 }}"
      komfovent_status_free_cooling:
        friendly_name: "Komfovent Status - Free Cooling"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(1024) > 0 }}"
      komfovent_status_alarm_f:
        friendly_name: "Komfovent Status - Alarm F"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(2048) > 0 }}"
      komfovent_status_alarm_w:
        friendly_name: "Komfovent Status - Alarm W"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(4096) > 0 }}"
```

![Image](https://github.com/user-attachments/assets/6f8b8f37-b0d8-4f13-8829-3a69e3338fc3)

### Describe alternatives you've considered

Nil

### Additional context

Nil
